### ISSUE TITLE
JWTService정의

### ISSUE THREAD

**Issue by sunwon12** [Flint-org/Flint-API-Server#18]
## 스프링 시큐리티 및 회원가입/ 로그인 정의 
- [x] JWTService 정의
- [x] application-jwt.yml에 access,refresh token 만료 시간 정의
- [x] application-jwt.yml에 access,refresh token 시크릿 값 정의

**Comment by SeungGun** [comment]
혹시 refresh token 정책도 사용하실 계획 있으신가요?

**Comment by kimgihean** [comment]
refresh token 을 사용하는게 JWT를 쓰는 이유라고 생각합니다.

access token 과 refresh token 만료 시간 정책에 대해서 논의해봐야 할 것 같습니다!

**Comment by sunwon12** [comment]
> 

정확하게 말하면 JWT를 쓰는 이유는  따로 서버의 메모리에 저장 공간을 확보할 필요가 없어서 입니당
refresh token가 주가 아닌 것 같습니다. 근데 refresh token을 쓰면 좋기 때문에 refresh token까지 개발하겠습니당

**Comment by sunwon12** [comment]
![image](https://github.com/Flint-org/Flint-API-Server/assets/92251131/f754bd8c-b049-4f05-9451-03031b6fc46d)

출처: https://wildeveloperetrain.tistory.com/245

**Comment by sunwon12** [comment]
찾아보니
accessToken은 30~60분 정도
refreshToken은 일주일 정도의 만료시간이 적당하다고 하네용
