### ISSUE TITLE
AWS 개발용 서버 구축하기

### ISSUE THREAD

**Issue by SeungGun** [Flint-org/Flint-API-Server#23]
## 작업할 내용
~~[ ] CI/CD 인스턴스 구축 (EC2)~~
- [x] WAS 인스턴스 구축 (EC2)
- [x] 미디어 스토리지 서버 구축 (S3) 
- [x] MySQL 데이터베이스 서버 구축 (RDS)
- [x] ssh 키, DB, 스토리지 서버 호스트 & 포트 정보 공유

**Comment by kimgihean** [comment]
웹이랑와스는 하나의 인스턴스에 3개씩 하실껀가요?

**Comment by SeungGun** [comment]
> 웹이랑와스는 하나의 인스턴스에 3개씩 하실껀가요?

인스턴스 분배 부분에 대한 아이디어 부탁드려용
일단 작성해놓은거라
