### ISSUE TITLE
대학생 인증 API 정의

### ISSUE THREAD

**Issue by sunwon12** [Flint-org/Flint-API-Server#26]
## 작업할 내용
- [x] 대학생 인증 API 2가지

1. 사용자에게 인증이메일 보내기
    1.  데이터베이스에서 사용자의 학교 이메일의 주소가 있는지 비교
    2.   인증코드를 만들어 이메일 보내기
         
2. 역활 바꿔주기(인증 안한 유저 → 인증 한 유저) API
    1. 프론트에서 인증코드를 확인했으면 백엔드에게 역활 바꿔주기를로 요청한다.
    
    
    
    논의할점:
     학교이메일인지 아닌지는 프론트에서 검증하는 것이 맞을까요 저희가 요청이 들어오면 검증하는 것이 맞을까요?
    제 생각은 사용자가 인증이메일 발송 버튼을 누르기 전 학교이메일이 맞는지 아닌지 검증당하는 게 맞다고 생각합니다.

**Comment by sunwon12** [comment]
@SeungGun @kimgihean

**Comment by SeungGun** [comment]
기능 요구사항 상으로는 앱에서 학교를 선택하면 학교 이메일 부분이 자동으로 채워지도록 하기로 되어있어서 그런 정보를 요청하
는 API만 별도로 만들기만 하면 학교 이메일인지 아닌지를 검증할 필요는 없을거같은데요?

**Comment by sunwon12** [comment]
> 기능 요구사항 상으로는 앱에서 학교를 선택하면 학교 이메일 부분이 자동으로 채워지도록 하기로 되어있어서 그런 정보를 요청하 는 API만 별도로 만들기만 하면 학교 이메일인지 아닌지를 검증할 필요는 없을거같은데요?

제가 기능요구사항을 꼼꼼히 보지 않았나 봅니다 하핫...
다음부터 꼼꼼히 보겠습니다
