### ISSUE TITLE
Feat: 자신 명함 API 작성

### ISSUE THREAD

**Issue by sunwon12** [Flint-org/Flint-API-Server#36]
## 작업할 내용

- [x] 명합뒷면 요구사항 변경에 따른 IdCard 엔티티 수정
  - [x]  cardBackExpercience 삭제
  - [x] cardFrontSNSId -> cardBackSNSId
  - [x] cardBackMBTI 추가
  - [x] cardBackInterests
  - [x] Interest ENUM 리스트 추가 
  - [x] ERDCloud에 수정
  
- [x] 명함 뒷면 관심사 요구사항 변경에 따른 Interest ENUM 생성(그림 그리기, 게임, 맛집 탐방 등 데이터베이스 입력 예정)

- [x] 자신 명함 API 작성
  - [x] 명함 앞면 자동 생성 API(학교 별 RGB 값 데이터는 승건님이 학교데이터 다루는 서비스 만든 후 추가/ 학교인증 한 유저만/ 이름, 이메일, 대학교, 전공 정보, 학번, 대학별 RGB)

- [x] 맴버 엔티티 구조 수정

의논해야 할 점: 
1. 명함 수정 기능
]  아래 그림 항목들을 수정할 수 있습니다.  
바뀌었는지 모든 속성(이메일,mbti,SNS, 키워드)들을 데이터베이스에서 조회후 값을 비교해야 하나 프론트에서 바뀐 속성의 이름을 따로 받고 그 에 해당하는 값만 데이터베이스에 업데이트를 해야 하나. 혹은 다른 방법이 있다면 알려주세용

![image](https://github.com/Flint-org/Flint-API-Server/assets/92251131/247eb6f1-620c-46ac-9b81-bd5a04776702)

2. 맴버 엔티티 수정
![image](https://github.com/Flint-org/Flint-API-Server/assets/92251131/8e6ed0a0-d2d5-458b-88c3-d11387373cbd)
club, community가 들어간 엔티티 각 club, community에 옮기는 거 어떤 가요?

**Comment by SeungGun** [comment]
너무 많은 테스크가 하나의 이슈에 몰아져 있습니다 분리 부탁드려요

**Comment by SeungGun** [comment]
의논해야할 부분에 대해서
1번의 경우에는 JPA 관점에서 사용해야되서 전체를 받고 전부 다 갈아끼우면 자동으로 바뀐 것만 업데이트 시켜줍니다. 경우에 따라서는 값 전체를 삭제하고 다 갈아끼우는 경우도 있던걸로 기억합니다.

2번의 경우에는 과연 해당 엔티티가 유저 관할인가 생각하시면 되는데 club, community가 포함된 모든 것은 옮기기 보다는 유동적으로 적절한 도메인 분리를 해주시면 될거같습니다.
