### ISSUE TITLE
QueryDsl과 Rest Docs 의존성 및 설정을 추가한다.

### ISSUE THREAD

**Issue by SeungGun** [Flint-org/Flint-API-Server#8]
## 작업할 내용
- [x] QueryDsl 의존성 및 그에 따른 설정 추가
- [x] Spring Rest Docs 의존성 및 그에 따른 설정 추가

**Comment by kimgihean** [comment]
QueryDsl 쓰실 때 repo 어떤 식으로 받나요?
전 JPA 상속 받는 repo가 QueryDsl 인터페이스까지 상속받도록 해서 Jpa 상속 받는 repo에서 QueryDsl method까지 쓸 수 있도록 해왔습니다!!

**Comment by SeungGun** [comment]
> QueryDsl 쓰실 때 repo 어떤 식으로 받나요? 전 JPA 상속 받는 repo가 QueryDsl 인터페이스까지 상속받도록 해서 Jpa 상속 받는 repo에서 QueryDsl method까지 쓸 수 있도록 해왔습니다!!

아래와 같은 방법으로 사용하신다는 말씀이시죠?

CustomRepository가 queryDsl에 대한 인터페이스라고 가정하면
```java
public interface Repository extends JpaRepository<Entity, Long>, CustomRepository { ... }
```

만약에 맞다면 저도 동일하게 사용해왔습니다!

**Comment by kimgihean** [comment]
네네 맞습니다!
```java
public interface DomainRepository extends JpaRepository<Domain, Long>, CustomRepository { ... }

public class CustomRepositoryImpl implements CustomRepository { ... }
```
이런식으로 구현했던거 같아요!

빈주입 할 config 파일도 만들어주고용.

다른 방법이 두갠가? 더 있었던걸로 아는데 승건님은 어떻게 구성하실지 궁금했습니다~
