### ISSUE TITLE
유저 및 이와 관련된 엔티티 작성

### ISSUE THREAD

**Issue by sunwon12** [Flint-org/Flint-API-Server#9]
## 유저 및 이와 연관된 엔티티(알림, 모임 차단 유저, 게시글 차단 유저, 학교인증, 명함, ouath카테고리) 작성
- [x] 유저 엔티티 작성
- [x] 모임 차단 유저 엔티티 작성
- [x] 게시글 차단 유저 엔티티 작성
- [x] 학교인증 엔티티 작성
- [x] 명함 엔티티 작성
- [x] #14

**Comment by kimgihean** [comment]
밤에도 일하는 당신 대단해...

**Comment by sunwon12** [comment]
알바가 지금 끝났습니다...

**Comment by kimgihean** [comment]
그럼 그냥 자고 일어나서 하지 ㅜㅜ

**Comment by sunwon12** [comment]
다들 열심히 하시는데 저도 못 참습니다!!
